// Tournament data — shared between seed script & Next.js app

export const GROUPS = {
  MS: {
    A: ['Jobin', 'George K.', 'Shaun', 'Nishant'],
    B: ['Levin', 'Jacob Kurien', 'Jithin', 'Deepak E.'],
    C: ['Ajin', 'George Mammen', 'Rev. John P. Joy', 'Abuttan'],
    D: ['Oby', 'Don', 'Reuben', 'Anil Raj'],
  },
  MD: {
    A: ['Linesh/ Anil', 'Don/Lijo', 'Ari Kombans'],
    B: ['George Thomas/ Manoj Abraham', 'Reuben/ Libin', 'SamThome', 'Cruise Control'],
    C: ['Smash', 'Crusaders', 'Beef Curry Blasters'],
    D: ['Kalikootukar', 'George K./ Abuttan', 'Robin C. / Oby'],
  },
  MXD: {
    'A/D': ['George M./ Tanya', 'Ansa/ Jobin', 'Reuben/ Shweta', 'Georges', 'Ajin/ Neenu'],
    'B/C': ['Team Mowgli', 'Mekha/ Issac', 'Smash & Dash', 'Net-work Issues', 'Net Ninjas'],
  },
  WS: {
    A: ['Tintu', 'Sneha', 'Shilpa'],
    B: ['Ansa', 'Nidhi', 'Mekha'],
  },
  WD: {
    A: ['Ansa/ Shilpa', 'Curl Power'],
    B: ['Blazing Birdies', 'Kilukkam'],
  },
};

export const TEAM_ROSTERS = {
  'Ari Kombans': ['Satish', 'Shaji'],
  'SamThome': ['Sam', 'Jacob'],
  'Cruise Control': ['Levin', 'Jerrin'],
  'Crusaders': ['Jobin', 'Shaun'],
  'Smash': ['George Mammen', 'Charlie'],
  'Beef Curry Blasters': ['Nishant', 'Deepak E.'],
  'Team Mowgli': ['Nidhi', 'Deepak'],
  'Smash & Dash': ['Don', 'Cheryl'],
  'Net-work Issues': ['Aida', 'Levin'],
  'Net Ninjas': ['Tintu', 'Shaun'],
  'Georges': ['Sneha', 'Nishant'],
  'Blazing Birdies': ['Tintu', 'Mekha'],
  'Kilukkam': ['Aida', 'Sneha'],
  'Curl Power': ['Cheryl', 'Tanya'],
};

export const CAT_LABELS = {
  MS: "Men's Singles", MD: "Men's Doubles", MXD: "Mixed Doubles",
  WS: "Women's Singles", WD: "Women's Doubles",
};

// Aliases: maps the name as it appears in SCHEDULE → the name as it appears in GROUPS.
// Used by the standings calculator when the two sheets differ (common for doubles
// where the schedule abbreviates).
export const NAME_ALIASES = {
  'George Thomas/Manoj': 'George Thomas/ Manoj Abraham',
};

export const SCHEDULE = [
  { id: 'm001', time: '13:00', court: 1, p1: 'Rev. John P. Joy', p2: 'George Mammen', umpire: 'Satish', cat: 'MS' },
  { id: 'm002', time: '13:00', court: 2, p1: 'Crusaders', p2: 'Beef Curry Blasters', umpire: 'Don', cat: 'MD' },
  { id: 'm003', time: '13:00', court: 3, p1: 'Team Mowgli', p2: 'Net-work Issues', umpire: 'Charlie', cat: 'MXD' },
  { id: 'm004', time: '13:12', court: 1, p1: 'Reuben', p2: 'Anil Raj', umpire: 'Jerrin', cat: 'MS' },
  { id: 'm005', time: '13:12', court: 2, p1: 'George M./Tanya', p2: 'Ansa/Jobin', umpire: 'Jacob T.', cat: 'MXD' },
  { id: 'm006', time: '13:12', court: 3, p1: 'Jacob Kurien', p2: 'Jithin', umpire: 'Lijo', cat: 'MS' },
  { id: 'm007', time: '13:24', court: 1, p1: 'Rev. John P. Joy', p2: 'Abuttan', umpire: 'Linesh', cat: 'MS' },
  { id: 'm008', time: '13:24', court: 2, p1: 'Team Mowgli', p2: 'Smash & Dash', umpire: 'Ajin', cat: 'MXD' },
  { id: 'm009', time: '13:24', court: 3, p1: 'Net-work Issues', p2: 'Net Ninjas', umpire: 'George M.', cat: 'MXD' },
  { id: 'm010', time: '13:36', court: 1, p1: 'Reuben/Shweta', p2: 'Georges', umpire: 'Satish', cat: 'MXD' },
  { id: 'm011', time: '13:36', court: 2, p1: 'Ansa', p2: 'Mekha', umpire: 'Don', cat: 'WS' },
  { id: 'm012', time: '13:36', court: 3, p1: 'Jobin', p2: 'George K.', umpire: 'Charlie', cat: 'MS' },
  { id: 'm013', time: '13:48', court: 1, p1: 'Ajin', p2: 'Rev. John P. Joy', umpire: 'Jobin', cat: 'MS' },
  { id: 'm014', time: '13:48', court: 2, p1: 'Smash & Dash', p2: 'Net Ninjas', umpire: 'Sam', cat: 'MXD' },
  { id: 'm015', time: '13:48', court: 3, p1: 'Mekha/ Issac', p2: 'Net-work Issues', umpire: 'Lijo', cat: 'MXD' },
  { id: 'm016', time: '14:00', court: 1, p1: 'Linesh/Anil', p2: 'Ari Kombans', umpire: 'George T.', cat: 'MD' },
  { id: 'm017', time: '14:00', court: 2, p1: 'Sneha', p2: 'Shilpa', umpire: 'Jacob T.', cat: 'WS' },
  { id: 'm018', time: '14:00', court: 3, p1: 'Jobin', p2: 'Nishant', umpire: 'George M.', cat: 'MS' },
  { id: 'm019', time: '14:12', court: 1, p1: 'Smash', p2: 'Crusaders', umpire: 'Jithin', cat: 'MD' },
  { id: 'm020', time: '14:12', court: 2, p1: 'Smash & Dash', p2: 'Net-work Issues', umpire: 'Tintu', cat: 'MXD' },
  { id: 'm021', time: '14:12', court: 3, p1: 'Team Mowgli', p2: 'Mekha/ Issac', umpire: 'Linesh', cat: 'MXD' },
  { id: 'm022', time: '14:24', court: 1, p1: 'Kalikootukar', p2: 'George K./Abuttan', umpire: 'Jacob T.', cat: 'MD' },
  { id: 'm023', time: '14:24', court: 2, p1: 'Levin', p2: 'Jithin', umpire: 'Deepak E.', cat: 'MS' },
  { id: 'm024', time: '14:24', court: 3, p1: 'Don', p2: 'Reuben', umpire: 'Sam', cat: 'MS' },
  { id: 'm025', time: '14:36', court: 1, p1: 'George K./Abuttan', p2: 'Robin C./Oby', umpire: 'Shaun', cat: 'MD' },
  { id: 'm026', time: '14:36', court: 2, p1: 'Nidhi', p2: 'Mekha', umpire: 'Shaji', cat: 'WS' },
  { id: 'm027', time: '14:36', court: 3, p1: 'Georges', p2: 'Ajin/Neenu', umpire: 'Anil Raj', cat: 'MXD' },
  { id: 'm028', time: '14:48', court: 1, p1: 'Levin', p2: 'Jacob Kurien', umpire: 'George T.', cat: 'MS' },
  { id: 'm029', time: '14:48', court: 2, p1: 'Ajin', p2: 'George Mammen', umpire: 'George K.', cat: 'MS' },
  { id: 'm030', time: '14:48', court: 3, p1: 'Linesh/Anil', p2: 'Don/Lijo', umpire: 'Sam', cat: 'MD' },
  { id: 'm031', time: '15:00', court: 1, p1: 'Team Mowgli', p2: 'Net Ninjas', umpire: 'Jerrin', cat: 'MXD' },
  { id: 'm032', time: '15:00', court: 2, p1: 'Ansa/Jobin', p2: 'Reuben/Shweta', umpire: 'Linesh', cat: 'MXD' },
  { id: 'm033', time: '15:00', court: 3, p1: 'George M./Tanya', p2: 'Georges', umpire: 'Jacob T.', cat: 'MXD' },
  { id: 'm034', time: '15:12', court: 1, p1: 'Mekha/ Issac', p2: 'Smash & Dash', umpire: 'Shaun', cat: 'MXD' },
  { id: 'm035', time: '15:12', court: 2, p1: 'Kalikootukar', p2: 'Robin C./Oby', umpire: 'Charlie', cat: 'MD' },
  { id: 'm036', time: '15:12', court: 3, p1: 'Oby', p2: 'Anil Raj', umpire: 'Levin', cat: 'MS' },
  { id: 'm037', time: '15:24', court: 1, p1: 'Smash', p2: 'Beef Curry Blasters', umpire: 'Sam', cat: 'MD' },
  { id: 'm038', time: '15:24', court: 2, p1: 'Reuben/Libin', p2: 'Cruise Control', umpire: 'Deepak E.', cat: 'MD' },
  { id: 'm039', time: '15:24', court: 3, p1: 'Ansa/Jobin', p2: 'Ajin/Neenu', umpire: 'Jithin', cat: 'MXD' },
  { id: 'm040', time: '15:36', court: 1, p1: 'Mekha/ Issac', p2: 'Net Ninjas', umpire: 'Anil Raj', cat: 'MXD' },
  { id: 'm041', time: '15:36', court: 2, p1: 'Oby', p2: 'Don', umpire: 'Levin', cat: 'MS' },
  { id: 'm042', time: '15:36', court: 3, p1: 'George Thomas/Manoj', p2: 'SamThome', umpire: 'Linesh', cat: 'MD' },
  { id: 'm043', time: '15:48', court: 1, p1: 'Levin', p2: 'Deepak E.', umpire: 'Jithin', cat: 'MS' },
  { id: 'm044', time: '15:48', court: 2, p1: 'George K.', p2: 'Nishant', umpire: 'George M.', cat: 'MS' },
  { id: 'm045', time: '15:48', court: 3, p1: 'Ansa/Shilpa', p2: 'Curl Power', umpire: 'Manoj A.', cat: 'WD' },
  { id: 'm046', time: '16:00', court: 1, p1: 'Reuben/Shweta', p2: 'Ajin/Neenu', umpire: 'Sam', cat: 'MXD' },
  { id: 'm047', time: '16:00', court: 2, p1: 'Tintu', p2: 'Sneha', umpire: 'Jacob T.', cat: 'WS' },
  { id: 'm048', time: '16:00', court: 3, p1: 'Don', p2: 'Anil Raj', umpire: 'Levin', cat: 'MS' },
  { id: 'm049', time: '16:12', court: 1, p1: 'George Mammen', p2: 'Abuttan', umpire: 'George K.', cat: 'MS' },
  { id: 'm050', time: '16:12', court: 2, p1: 'Shaun', p2: 'Nishant', umpire: 'Anil Raj', cat: 'MS' },
  { id: 'm051', time: '16:12', court: 3, p1: 'George Thomas/Manoj', p2: 'Cruise Control', umpire: 'Satish', cat: 'MD' },
  { id: 'm052', time: '16:24', court: 1, p1: 'Jithin', p2: 'Deepak E.', umpire: 'Don', cat: 'MS' },
  { id: 'm053', time: '16:24', court: 2, p1: 'George M./Tanya', p2: 'Ajin/Neenu', umpire: 'Oby', cat: 'MXD' },
  { id: 'm054', time: '16:24', court: 3, p1: 'George M./Tanya', p2: 'Reuben/Shweta', umpire: 'Shaji', cat: 'MXD' },
  { id: 'm055', time: '16:36', court: 1, p1: 'George K.', p2: 'Shaun', umpire: 'Jerrin', cat: 'MS' },
  { id: 'm056', time: '16:36', court: 2, p1: 'SamThome', p2: 'Cruise Control', umpire: 'Charlie', cat: 'MD' },
  { id: 'm057', time: '16:36', court: 3, p1: 'George Thomas/Manoj', p2: 'Reuben/Libin', umpire: 'Jobin', cat: 'MD' },
  { id: 'm058', time: '16:48', court: 1, p1: 'Ansa', p2: 'Nidhi', umpire: 'Jithin', cat: 'WS' },
  { id: 'm059', time: '16:48', court: 2, p1: 'Ajin', p2: 'Abuttan', umpire: 'Oby', cat: 'MS' },
  { id: 'm060', time: '16:48', court: 3, p1: 'Jacob Kurien', p2: 'Deepak E.', umpire: 'Satish', cat: 'MS' },
  { id: 'm061', time: '17:00', court: 1, p1: 'Blazing Birdies', p2: 'Kilukkam', umpire: 'Manoj A.', cat: 'WD' },
  { id: 'm062', time: '17:00', court: 2, p1: 'Jobin', p2: 'Shaun', umpire: 'George K.', cat: 'MS' },
  { id: 'm063', time: '17:00', court: 3, p1: 'Reuben/Libin', p2: 'SamThome', umpire: 'George T.', cat: 'MD' },
  { id: 'm064', time: '17:12', court: 1, p1: 'Don/Lijo', p2: 'Ari Kombans', umpire: 'George M.', cat: 'MD' },
  { id: 'm065', time: '17:12', court: 2, p1: 'Tintu', p2: 'Shilpa', umpire: 'Satish', cat: 'WS' },
  { id: 'm066', time: '17:12', court: 3, p1: 'Semi: WS Group A2 vs B1', p2: null, umpire: 'Charlie', cat: 'WS', isPlayoff: true, stage: 'Semi', label: "Women's Singles Semi — A2 vs B1" },
  { id: 'm067', time: '17:24', court: 1, p1: 'Ansa/Jobin', p2: 'Georges', umpire: 'Shaji', cat: 'MXD' },
  { id: 'm068', time: '17:24', court: 2, p1: 'Oby', p2: 'Reuben', umpire: 'Anil Raj', cat: 'MS' },
  { id: 'm069', time: '17:24', court: 3, p1: 'Semi: WS Group A1 vs B2', p2: null, umpire: 'Jacob T.', cat: 'WS', isPlayoff: true, stage: 'Semi', label: "Women's Singles Semi — A1 vs B2" },
  { id: 'm070', time: '17:36', court: 1, p1: 'Semi: MS Group A vs D winner', p2: null, cat: 'MS', isPlayoff: true, stage: 'Semi', label: "Men's Singles Semi — Group A vs D winner" },
  { id: 'm071', time: '17:36', court: 2, p1: 'Semi: MS Group B vs C winner', p2: null, cat: 'MS', isPlayoff: true, stage: 'Semi', label: "Men's Singles Semi — Group B vs C winner" },
  { id: 'm072', time: '17:36', court: 3, p1: 'Semi: MD Group A vs D winner', p2: null, cat: 'MD', isPlayoff: true, stage: 'Semi', label: "Men's Doubles Semi — Group A vs D winner" },
  { id: 'm073', time: '18:00', court: 1, p1: 'Semi: MXD Group AD1 vs BC2 winner', p2: null, cat: 'MXD', isPlayoff: true, stage: 'Semi', label: "Mixed Doubles Semi — AD1 vs BC2" },
  { id: 'm074', time: '18:00', court: 2, p1: 'Semi: MD Group B vs C winner', p2: null, cat: 'MD', isPlayoff: true, stage: 'Semi', label: "Men's Doubles Semi — Group B vs C winner" },
  { id: 'm075', time: '18:00', court: 3, p1: 'Semi: MXD Group AD2 vs BC1 winner', p2: null, cat: 'MXD', isPlayoff: true, stage: 'Semi', label: "Mixed Doubles Semi — AD2 vs BC1" },
  { id: 'm076', time: '18:25', court: 1, p1: 'Finals: MS', p2: null, cat: 'MS', isPlayoff: true, stage: 'Final', label: "Men's Singles Final" },
  { id: 'm077', time: '18:25', court: 2, p1: 'Semi: WD Group A2 vs B1', p2: null, cat: 'WD', isPlayoff: true, stage: 'Semi', label: "Women's Doubles Semi — A2 vs B1" },
  { id: 'm078', time: '18:25', court: 3, p1: 'Semi: WD Group A1 vs B2', p2: null, cat: 'WD', isPlayoff: true, stage: 'Semi', label: "Women's Doubles Semi — A1 vs B2" },
  { id: 'm079', time: '18:50', court: 1, p1: 'Finals: MD', p2: null, cat: 'MD', isPlayoff: true, stage: 'Final', label: "Men's Doubles Final" },
  { id: 'm080', time: '18:50', court: 2, p1: 'Finals: WS', p2: null, cat: 'WS', isPlayoff: true, stage: 'Final', label: "Women's Singles Final" },
  { id: 'm081', time: '18:50', court: 3, p1: 'Finals: WD', p2: null, cat: 'WD', isPlayoff: true, stage: 'Final', label: "Women's Doubles Final" },
  { id: 'm082', time: '19:15', court: 1, p1: 'Finals: MXD', p2: null, cat: 'MXD', isPlayoff: true, stage: 'Final', label: "Mixed Doubles Final" },
];
