// AUTO-GENERATED tournament data
// UPDATED: Labels now use "SEMI 1", "SEMI 2" format
// Total: 116 matches (m1-m72 prelims, m73-m117 semi/final sets)

export const SCHEDULE = [
  { id: 'm1', time: '13:00', court: 1, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Satish', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm2', time: '13:00', court: 2, cat: 'WD', p1: 'TBD', p2: 'TBD', umpire: 'Don', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'WD Prelim' },
  { id: 'm3', time: '13:00', court: 3, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Charlie', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm4', time: '13:12', court: 1, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Jerrin', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm5', time: '13:12', court: 2, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Sam', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm6', time: '13:12', court: 3, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Lijo', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm7', time: '13:24', court: 1, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Linesh', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm8', time: '13:24', court: 2, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Ajin', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm9', time: '13:24', court: 3, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'George M.', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm10', time: '13:36', court: 1, cat: 'MXD', p1: 'TBD', p2: 'TBD', umpire: 'Satish', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MXD Prelim' },
  { id: 'm11', time: '13:36', court: 2, cat: 'WS', p1: 'TBD', p2: 'TBD', umpire: 'Don', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'WS Prelim' },
  { id: 'm12', time: '13:36', court: 3, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Charlie', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm13', time: '13:48', court: 1, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Jobin', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm14', time: '13:48', court: 2, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Sam', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm15', time: '13:48', court: 3, cat: 'WD', p1: 'TBD', p2: 'TBD', umpire: 'Lijo', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'WD Prelim' },
  { id: 'm16', time: '14:00', court: 1, cat: 'MD', p1: 'TBD', p2: 'TBD', umpire: 'George T.', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MD Prelim' },
  { id: 'm17', time: '14:00', court: 2, cat: 'WD', p1: 'TBD', p2: 'TBD', umpire: 'Satish', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'WD Prelim' },
  { id: 'm18', time: '14:00', court: 3, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'George M.', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm19', time: '14:12', court: 1, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Jithin', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm20', time: '14:12', court: 2, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Tintu', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm21', time: '14:12', court: 3, cat: 'WD', p1: 'TBD', p2: 'TBD', umpire: 'Linesh', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'WD Prelim' },
  { id: 'm22', time: '14:24', court: 1, cat: 'MD', p1: 'TBD', p2: 'TBD', umpire: 'Jerrin', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MD Prelim' },
  { id: 'm23', time: '14:24', court: 2, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Deepak E.', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm24', time: '14:24', court: 3, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Sam', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm25', time: '14:36', court: 1, cat: 'MD', p1: 'TBD', p2: 'TBD', umpire: 'Shaun', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MD Prelim' },
  { id: 'm26', time: '14:36', court: 2, cat: 'WS', p1: 'TBD', p2: 'TBD', umpire: 'Shaji', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'WS Prelim' },
  { id: 'm27', time: '14:36', court: 3, cat: 'MXD', p1: 'TBD', p2: 'TBD', umpire: 'Anil Raj', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MXD Prelim' },
  { id: 'm28', time: '14:48', court: 1, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'George T.', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm29', time: '14:48', court: 2, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'George K.', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm30', time: '14:48', court: 3, cat: 'MD', p1: 'TBD', p2: 'TBD', umpire: 'Sam', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MD Prelim' },
  { id: 'm31', time: '15:00', court: 1, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Jerrin', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm32', time: '15:00', court: 2, cat: 'WD', p1: 'TBD', p2: 'TBD', umpire: 'Linesh', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'WD Prelim' },
  { id: 'm33', time: '15:00', court: 3, cat: 'MXD', p1: 'TBD', p2: 'TBD', umpire: 'Lijo', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MXD Prelim' },
  { id: 'm34', time: '15:12', court: 1, cat: 'WD', p1: 'TBD', p2: 'TBD', umpire: 'Shaun', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'WD Prelim' },
  { id: 'm35', time: '15:12', court: 2, cat: 'MD', p1: 'TBD', p2: 'TBD', umpire: 'Charlie', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MD Prelim' },
  { id: 'm36', time: '15:12', court: 3, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Levin', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm37', time: '15:24', court: 1, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Sam', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm38', time: '15:24', court: 2, cat: 'MD', p1: 'TBD', p2: 'TBD', umpire: 'Deepak E.', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MD Prelim' },
  { id: 'm39', time: '15:24', court: 3, cat: 'WD', p1: 'TBD', p2: 'TBD', umpire: 'Jithin', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'WD Prelim' },
  { id: 'm40', time: '15:36', court: 1, cat: 'WD', p1: 'TBD', p2: 'TBD', umpire: 'Anil Raj', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'WD Prelim' },
  { id: 'm41', time: '15:36', court: 2, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Levin', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm42', time: '15:36', court: 3, cat: 'MD', p1: 'TBD', p2: 'TBD', umpire: 'Linesh', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MD Prelim' },
  { id: 'm43', time: '15:48', court: 1, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Jithin', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm44', time: '15:48', court: 2, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'George M.', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm45', time: '15:48', court: 3, cat: 'WD', p1: 'TBD', p2: 'TBD', umpire: 'Manoj A.', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'WD Prelim' },
  { id: 'm46', time: '16:00', court: 1, cat: 'MD', p1: 'TBD', p2: 'TBD', umpire: 'TBD', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MD Prelim' },
  { id: 'm47', time: '16:00', court: 1, cat: 'MXD', p1: 'TBD', p2: 'TBD', umpire: 'Sam', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MXD Prelim' },
  { id: 'm48', time: '16:00', court: 2, cat: 'WS', p1: 'TBD', p2: 'TBD', umpire: 'Oby', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'WS Prelim' },
  { id: 'm49', time: '16:00', court: 3, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Levin', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm50', time: '16:12', court: 1, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'George K.', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm51', time: '16:12', court: 2, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Anil Raj', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm52', time: '16:12', court: 3, cat: 'MD', p1: 'TBD', p2: 'TBD', umpire: 'Satish', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MD Prelim' },
  { id: 'm53', time: '16:24', court: 1, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Charlie', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm54', time: '16:24', court: 2, cat: 'MXD', p1: 'TBD', p2: 'TBD', umpire: 'Oby', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MXD Prelim' },
  { id: 'm55', time: '16:24', court: 3, cat: 'WD', p1: 'TBD', p2: 'TBD', umpire: 'Shaji', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'WD Prelim' },
  { id: 'm56', time: '16:36', court: 1, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Jerrin', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm57', time: '16:36', court: 2, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Charlie', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm58', time: '16:36', court: 3, cat: 'MD', p1: 'TBD', p2: 'TBD', umpire: 'Jobin', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MD Prelim' },
  { id: 'm59', time: '16:48', court: 1, cat: 'WS', p1: 'TBD', p2: 'TBD', umpire: 'Jithin', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'WS Prelim' },
  { id: 'm60', time: '16:48', court: 2, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Oby', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm61', time: '16:48', court: 3, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Satish', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm62', time: '17:00', court: 1, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Manoj A.', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm63', time: '17:00', court: 2, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'George K.', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm64', time: '17:00', court: 3, cat: 'MD', p1: 'TBD', p2: 'TBD', umpire: 'George T.', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MD Prelim' },
  { id: 'm65', time: '17:12', court: 1, cat: 'MD', p1: 'TBD', p2: 'TBD', umpire: 'George M.', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MD Prelim' },
  { id: 'm66', time: '17:12', court: 2, cat: 'WD', p1: 'TBD', p2: 'TBD', umpire: 'Satish', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'WD Prelim' },
  { id: 'm67', time: '17:12', court: 3, cat: 'WD', p1: 'TBD', p2: 'TBD', umpire: 'Charlie', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'WD Prelim' },
  { id: 'm68', time: '17:24', court: 1, cat: 'WD', p1: 'TBD', p2: 'TBD', umpire: 'Shaji', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'WD Prelim' },
  { id: 'm69', time: '17:24', court: 2, cat: 'MS', p1: 'TBD', p2: 'TBD', umpire: 'Anil Raj', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MS Prelim' },
  { id: 'm71', time: '5:36 PM', court: 1, cat: 'WD', p1: 'TBD', p2: 'TBD', umpire: 'Linesh', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'WD Prelim' },
  { id: 'm72', time: '5:36 PM', court: 2, cat: 'MXD', p1: 'TBD', p2: 'TBD', umpire: 'Shaji', isPlayoff: false, matchType: 'prelim', scoringFormat: 15, label: 'MXD Prelim' },
  { id: 'm73', time: '17:24', court: 3, cat: 'WS', p1: 'WS: Group A2', p2: 'Group B1', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'WS SEMI 1' },
  { id: 'm74', time: '17:24', court: 3, cat: 'WS', p1: 'WS: Group A2', p2: 'Group B1', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'WS SEMI 2' },
  { id: 'm75', time: '17:24', court: 3, cat: 'WS', p1: 'WS: Group A2', p2: 'Group B1', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'WS SEMI 3' },
  { id: 'm76', time: '5:36 PM', court: 3, cat: 'WS', p1: 'WS: Group A1', p2: 'Group B2', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'WS SEMI 1' },
  { id: 'm77', time: '5:36 PM', court: 3, cat: 'WS', p1: 'WS: Group A1', p2: 'Group B2', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'WS SEMI 2' },
  { id: 'm78', time: '5:36 PM', court: 3, cat: 'WS', p1: 'WS: Group A1', p2: 'Group B2', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'WS SEMI 3' },
  { id: 'm79', time: '6:00 PM', court: 1, cat: 'MS', p1: 'MS- Group A', p2: 'Group D winner', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'MS SEMI 1' },
  { id: 'm80', time: '6:00 PM', court: 1, cat: 'MS', p1: 'MS- Group A', p2: 'Group D winner', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'MS SEMI 2' },
  { id: 'm81', time: '6:00 PM', court: 1, cat: 'MS', p1: 'MS- Group A', p2: 'Group D winner', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'MS SEMI 3' },
  { id: 'm82', time: '6:00 PM', court: 2, cat: 'MS', p1: 'MS: Group B', p2: 'Group C winner', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'MS SEMI 1' },
  { id: 'm83', time: '6:00 PM', court: 2, cat: 'MS', p1: 'MS: Group B', p2: 'Group C winner', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'MS SEMI 2' },
  { id: 'm84', time: '6:00 PM', court: 2, cat: 'MS', p1: 'MS: Group B', p2: 'Group C winner', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'MS SEMI 3' },
  { id: 'm85', time: '6:00 PM', court: 3, cat: 'MD', p1: 'MD- Group A', p2: 'Group D Winner', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'MD SEMI 1' },
  { id: 'm86', time: '6:00 PM', court: 3, cat: 'MD', p1: 'MD- Group A', p2: 'Group D Winner', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'MD SEMI 2' },
  { id: 'm87', time: '6:00 PM', court: 3, cat: 'MD', p1: 'MD- Group A', p2: 'Group D Winner', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'MD SEMI 3' },
  { id: 'm88', time: '6:25 PM', court: 1, cat: 'WD', p1: 'WD: Group A2', p2: 'Group B1', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'WD SEMI 1' },
  { id: 'm89', time: '6:25 PM', court: 1, cat: 'WD', p1: 'WD: Group A2', p2: 'Group B1', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'WD SEMI 2' },
  { id: 'm90', time: '6:25 PM', court: 1, cat: 'WD', p1: 'WD: Group A2', p2: 'Group B1', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'WD SEMI 3' },
  { id: 'm91', time: '6:25 PM', court: 2, cat: 'MD', p1: 'MD: Group B', p2: 'Group C winner', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'MD SEMI 1' },
  { id: 'm92', time: '6:25 PM', court: 2, cat: 'MD', p1: 'MD: Group B', p2: 'Group C winner', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'MD SEMI 2' },
  { id: 'm93', time: '6:25 PM', court: 2, cat: 'MD', p1: 'MD: Group B', p2: 'Group C winner', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'MD SEMI 3' },
  { id: 'm94', time: '6:25 PM', court: 3, cat: 'MXD', p1: 'MXD: Group AD2', p2: 'Group BC1 winner', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'MXD SEMI 1' },
  { id: 'm95', time: '6:25 PM', court: 3, cat: 'MXD', p1: 'MXD: Group AD2', p2: 'Group BC1 winner', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'MXD SEMI 2' },
  { id: 'm96', time: '6:25 PM', court: 3, cat: 'MXD', p1: 'MXD: Group AD2', p2: 'Group BC1 winner', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'MXD SEMI 3' },
  { id: 'm97', time: '6:50 PM', court: 1, cat: 'MS', p1: 'MS', p2: 'TBD', umpire: 'TBD', isPlayoff: true, matchType: 'final', scoringFormat: 21, label: 'MS FINAL 1' },
  { id: 'm98', time: '6:50 PM', court: 1, cat: 'MS', p1: 'MS', p2: 'TBD', umpire: 'TBD', isPlayoff: true, matchType: 'final', scoringFormat: 21, label: 'MS FINAL 2' },
  { id: 'm99', time: '6:50 PM', court: 1, cat: 'MS', p1: 'MS', p2: 'TBD', umpire: 'TBD', isPlayoff: true, matchType: 'final', scoringFormat: 21, label: 'MS FINAL 3' },
  { id: 'm100', time: '6:50 PM', court: 2, cat: 'MXD', p1: 'MXD- Group AD1', p2: 'Group BC2 Winner', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'MXD SEMI 1' },
  { id: 'm101', time: '6:50 PM', court: 2, cat: 'MXD', p1: 'MXD- Group AD1', p2: 'Group BC2 Winner', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'MXD SEMI 2' },
  { id: 'm102', time: '6:50 PM', court: 2, cat: 'MXD', p1: 'MXD- Group AD1', p2: 'Group BC2 Winner', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'MXD SEMI 3' },
  { id: 'm103', time: '6:50 PM', court: 3, cat: 'WD', p1: 'WD: Group A1', p2: 'Group B2', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'WD SEMI 1' },
  { id: 'm104', time: '6:50 PM', court: 3, cat: 'WD', p1: 'WD: Group A1', p2: 'Group B2', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'WD SEMI 2' },
  { id: 'm105', time: '6:50 PM', court: 3, cat: 'WD', p1: 'WD: Group A1', p2: 'Group B2', umpire: 'TBD', isPlayoff: true, matchType: 'semi', scoringFormat: 21, label: 'WD SEMI 3' },
  { id: 'm106', time: '7:15 PM', court: 1, cat: 'MD', p1: 'MD', p2: 'TBD', umpire: 'TBD', isPlayoff: true, matchType: 'final', scoringFormat: 21, label: 'MD FINAL 1' },
  { id: 'm107', time: '7:15 PM', court: 1, cat: 'MD', p1: 'MD', p2: 'TBD', umpire: 'TBD', isPlayoff: true, matchType: 'final', scoringFormat: 21, label: 'MD FINAL 2' },
  { id: 'm108', time: '7:15 PM', court: 1, cat: 'MD', p1: 'MD', p2: 'TBD', umpire: 'TBD', isPlayoff: true, matchType: 'final', scoringFormat: 21, label: 'MD FINAL 3' },
  { id: 'm109', time: '7:15 PM', court: 2, cat: 'WS', p1: 'WS', p2: 'TBD', umpire: 'TBD', isPlayoff: true, matchType: 'final', scoringFormat: 21, label: 'WS FINAL 1' },
  { id: 'm110', time: '7:15 PM', court: 2, cat: 'WS', p1: 'WS', p2: 'TBD', umpire: 'TBD', isPlayoff: true, matchType: 'final', scoringFormat: 21, label: 'WS FINAL 2' },
  { id: 'm111', time: '7:15 PM', court: 2, cat: 'WS', p1: 'WS', p2: 'TBD', umpire: 'TBD', isPlayoff: true, matchType: 'final', scoringFormat: 21, label: 'WS FINAL 3' },
  { id: 'm112', time: '7:15 PM', court: 3, cat: 'WD', p1: 'WD', p2: 'TBD', umpire: 'TBD', isPlayoff: true, matchType: 'final', scoringFormat: 21, label: 'WD FINAL 1' },
  { id: 'm113', time: '7:15 PM', court: 3, cat: 'WD', p1: 'WD', p2: 'TBD', umpire: 'TBD', isPlayoff: true, matchType: 'final', scoringFormat: 21, label: 'WD FINAL 2' },
  { id: 'm114', time: '7:15 PM', court: 3, cat: 'WD', p1: 'WD', p2: 'TBD', umpire: 'TBD', isPlayoff: true, matchType: 'final', scoringFormat: 21, label: 'WD FINAL 3' },
  { id: 'm115', time: '7:30 PM', court: 1, cat: 'MXD', p1: 'MXD', p2: 'TBD', umpire: 'TBD', isPlayoff: true, matchType: 'final', scoringFormat: 21, label: 'MXD FINAL 1' },
  { id: 'm116', time: '7:30 PM', court: 1, cat: 'MXD', p1: 'MXD', p2: 'TBD', umpire: 'TBD', isPlayoff: true, matchType: 'final', scoringFormat: 21, label: 'MXD FINAL 2' },
  { id: 'm117', time: '7:30 PM', court: 1, cat: 'MXD', p1: 'MXD', p2: 'TBD', umpire: 'TBD', isPlayoff: true, matchType: 'final', scoringFormat: 21, label: 'MXD FINAL 3' },
];

// GROUPS (from spreadsheet)
export const GROUPS = {
  MS: {
    'Group A': ['Rev. John P. Joy', 'Abuttan', 'Ajin'],
    'Group B': ['Reuben', 'Anil Raj', 'George Mammen'],
    'Group C': ['Jacob Kurien', 'Jithin', 'Levin'],
    'Group D': ['Jobin', 'George K.', 'Deepak E.', 'Don', 'Nishant', 'Shaun', 'Oby']
  },
  MD: {
    'Group A': ['Linesh/Anil', 'Ari Kombans', 'Don/Lijo'],
    'Group B': ['Kalikootukar', 'George K./Abuttan', 'Robin C./Oby'],
    'Group C': ['Reuben/Libin', 'SamThome', 'Cruise Control'],
    'Group D': ['George Thomas/Manoj', 'Smash', 'Crusaders', 'Beef Curry Blasters']
  },
  MXD: {
    'Group AD': ['George M./Tanya', 'Ansa/Jobin', 'Reuben/Shweta', 'Georges', 'Ajin/Neenu'],
    'Group BC': ['Team Mowgli', 'Smash & Dash', 'Net-work Issues', 'Net Ninjas', 'Mekha/ Issac']
  },
  WS: {
    'Group A': ['Ansa', 'Mekha', 'Nidhi'],
    'Group B': ['Tintu', 'Sneha']
  },
  WD: {
    'Group A': ['Shilpa/Abuttan', 'Mekha/Issac'],
    'Group B': ['Blazing Birdies', 'Kilukkam', 'Ansa/Shilpa', 'Curl Power']
  }
};

// TEAM_ROSTERS
export const TEAM_ROSTERS = {
  'Team Mowgli': ['Aida', 'Cheryl'],
  'Smash & Dash': ['Issac', 'Tanya'],
  'Net-work Issues': ['George M.', 'Shweta'],
  'Net Ninjas': ['Neenu', 'Jobin'],
  'Georges': ['Georges', 'Jobin'],
  'Mekha/ Issac': ['Mekha', 'Issac'],
  'Blazing Birdies': ['Tintu', 'Sneha'],
  'Kilukkam': ['Ansa', 'Shilpa'],
  'Curl Power': ['Nidhi', 'Mekha'],
  'Crusaders': ['Sam', 'Linesh'],
  'Beef Curry Blasters': ['Don', 'Lijo'],
  'Smash': ['Ajin', 'Jobin'],
  'Ari Kombans': ['Satish', 'Shaji'],
  'Kalikootukar': ['Jerrin', 'Jithin'],
  'SamThome': ['Samuel', 'Thomachan'],
  'Cruise Control': ['Deepak E.', 'Manoj A.']
};

// CAT_LABELS
export const CAT_LABELS = {
  MS: "Men's Singles",
  MD: "Men's Doubles",
  WS: "Women's Singles",
  WD: "Women's Doubles",
  MXD: "Mixed Doubles"
};

// NAME_ALIASES
export const NAME_ALIASES = {
  'George Thomas/Manoj': 'George Thomas/ Manoj Abraham',
  'Linesh/Anil': 'Linesh/ Anil',
  'Ansa/Jobin': 'Ansa/ Jobin',
  'George M./Tanya': 'George M./ Tanya',
  'Mekha/ Issac': 'Mekha/Issac',
  'Shilpa/Abuttan': 'Shilpa/ Abuttan',
  'Reuben/Shweta': 'Reuben/ Shweta',
  'Ajin/Neenu': 'Ajin/ Neenu',
  'Reuben/Libin': 'Reuben/ Libin',
  'George K./Abuttan': 'George K./ Abuttan',
  'Robin C./Oby': 'Robin C./ Oby',
  'Don/Lijo': 'Don/ Lijo',
  'Ansa/Shilpa': 'Ansa/ Shilpa'
};
